# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test_eventgen:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Enable Py3
          command: |
            pyenv uninstall  -f 3.5.2
            sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
              libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils git \
              libffi-dev liblzma-dev python-openssl
            pyenv install 3.7.7
            pyenv global 3.7.7
      - run:
          name: Run Tests
          command: |
            set -e
            make test
          no_output_timeout: 30m
      - store_test_results:
          path: /home/circleci/project/tests/test-reports
      - store_artifacts:
          path: /home/circleci/project/tests/test-reports
      - store_artifacts:
          path: /home/circleci/project/htmlcov

workflows:
  version: 2
  run_tests:
    jobs:
      - test_eventgen

