# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test_eventgen:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Enable Py3
          command: |
            pyenv global 3.7.0
      - run:
          name: Check Code Format
          command: |
            set -e
            pip install -r requirements.txt
            make format-check
      - run:
          name: Run Tests
          command: |
            set -e
            make test
          no_output_timeout: 30m
      - store_test_results:
          path: /home/circleci/project/tests/test-reports
      - store_artifacts:
          path: /home/circleci/project/tests/test-reports
      - store_artifacts:
          path: /home/circleci/project/htmlcov

workflows:
  version: 2
  run_tests:
    jobs:
      - test_eventgen

